package com.damonkelley.accountant.budget.application

import com.damonkelley.accountant.budget.domain.Budget
import com.damonkelley.accountant.eventsourcing.ExistingAggregateRootProvider
import com.damonkelley.accountant.eventsourcing.NewAggregateRootProvider

interface NewBudgetProvider : NewAggregateRootProvider<Budget>
interface ExistingBudgetProvider: ExistingAggregateRootProvider<Budget>